 Урок 2

In [51]:
#1. Установить, какие произведения матриц AB и BA определены, и найти размерности полученных матри
#а) A — матрица 4 × 2, B — матрица 4 × 2;
#б) A — матрица 2 × 5, B — матрица 5 × 3;
#в) A — матрица 8 × 3, B — матрица 3 × 8;
#г) A — квадратная матрица 4 × 4, B — квадратная матрица 4 × 4

In [6]:
import numpy as np
#а) не определены АВ, ВА б) определено АВ р=2*3 в) определены АВ р= 8*8, ВА р= 3*3  г) определены АВ,ВА р = 4*4

In [7]:
#                                            1 −2          4 −1
#2. Найти сумму и произведение матриц A =    3  0   и B =  0  5

In [8]:
#       5 -3           1*4+0*(-2)  1*(-1)+(-2)*5   4  -11
# А+В = 3  5      A*B =3*4+0*0     3*(-1)+0*5    = 12  -3 

In [12]:
A=np.array([[1,-2],[3,0]]); B=np.array([[4,-1],[0,5]])
print(A+B)
print(np.dot(A,B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы
одного размера образуют линейное пространство. Вычислить линейную комбинацию 3A − 2B + 4C для
           1  7     0  5      2 −4  
матриц A = 3 −6, B =2 −1, C = 1  1

In [14]:
#                   3*1-2*0+4*2   3*7-2*5-4*4  11   -5
#    3A − 2B + 4C = 3*3-2*2+4*1  -3*6+2*1+4*1 = 9  -12
A=np.array([[1,7],[3,-6]]); B=np.array([[0,5],[2,-1]]); C=np.array([[2,-4],[1,1]]); 
print(3*A -2*B +4*C)

[[ 11  -5]
 [  9 -12]]


In [ ]:
#                     4  1   T                      T     T 
#4. Дана матрица A =  5 -2  A = 4  5 2   Вычислить A A и A А
#                     2  3      1 -2 3    

In [16]:
#   T   4*4+1*1 4*5-1*2 4*2+1*3   17  18 11
# AA  = 5*4-2*1 5*5+2*2 5*2-2*3 = 18  29  4
#       2*4+3*1 2*5-3*2 2*2+3*3   11   4 13

# T   
#A A  = 4*4 + 5*5 + 2*2  4*1 - 5*2 + 2*3 = 45  0  
#       1*4 - 2*5 + 3*2  1*1 + 2*2 + 3*3    0 14
A=np.array([[4,1],[5,-2],[2,3]])
print(np.dot(A,A.T))
print(np.dot(A.T,A))


[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [50]:
# без излишних проверок..
def MtrxMul(A,B):
    (mA,nA),(mB,nB) = A.shape,B.shape 
    R = np.zeros((mA,nB))
    if nA==mB:
        for i in range(mA):
            for j in range(nB):
                R[i,j] = sum(A[i,:]*B[:,j])
    else:
        R = 'matrixs have unproper size!!' 
    return R

A=np.array([[1,1],[1,-1],[1,1]])
B=np.array([[2,2,2,2,2,2,2,2,2],[2,2,2,2,2,2,2,2,2]])

print(MtrxMul(A,B))

[[4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4.]]


In [55]:
# Lesson 4
# 1. Вычислить определитель:
#a) sinx*sinx-(-cosx*cosx) = 1
#б)| 4 2 3|
#  | 0 5 1|  = 4*5*9 = 180 (треугольная!)
#  | 0 0 9|

#в)| 1 2 3|
#  | 4 5 6|  = 1*(5*9-6*8) -2*(4*9-6*7) + 3*(4*8-5*7)= -3+12-9 = 0
#  | 7 8 9|

A=np.array([[4,2,3],[0,5,1],[0,0,9]]); print(np.linalg.det(A))
A=np.array([[1,2,3],[4,5,6],[7,8,9]]); print(np.linalg.det(A))

180.0
6.66133814775094e-16


In [ ]:
#2. det(A)=4 => det(A^2)=det(A)*det(A)=16; det(A.T)=4; det(2A)=4*2^rank. т.е. для rank=1 - det(2A)=8, 2 - 16, 3 - 32 и т.д.

In [56]:
#3 матрица вырожденная, поскольку первая и вторая ее строки линейно зависимы
A=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]]); print(np.linalg.det(A))

0.0


In [57]:
#4 a) сама матрица вырожденная, т.к.вторая строка равна разности третьей и первой,
#     зато можно найти ненулевой минор второго порядка:
#1 2
#1 1 det=-1, rank = 2

#b) 0 0 2 1  ранг 3, т.к. из первых трех строк только одна линейно зависимая
#   0 0 2 2
#   0 0 4 3
#   2 3 5 6
#
A=np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]]); print(np.linalg.matrix_rank(A))

3
