 Урок 4

In [1]:
import numpy as np

In [2]:
#1. Решить систему уравнений методом Гаусса:
#
#  x1 + x2 − x3 − 2x4 = 0,
# 2x1 + x2 − x3 + x4 = −2,
#  x1 + x2 − 3x3 + x4 = 4.
#
# Число переменных больше числа уравнений - система недоопределена, решений бесконечное число.
# Отыщем структуру этих решений:
# 2x1 + x2 − x3 +   x4 = −2, (2e)
#       x2 − x3 + -5x4 =  2,(2*1e-2e)
#           2x3 + -3x4 = -4 (1e-3e)
# тогда, если x4=c, то x3=1.5c-2, x2=6.5c, x1=-2-3c
#

In [50]:
#2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:
#a) 
# 3x1 − x2 + x3 = 4,
# 2x1 − 5x2 − 3x3 = −17,
# x1 + x2 − x3 = 0;
# число неизвестных равно числу уравнений (3), определитель матрицы коэфф. не равен нулю: решение одно.
# по т.Кронеккера: rank(A)=rank(A~)=3:                                                    решение одно.
A=np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
f=np.array([4,-17,0])

print('a)')
print(np.linalg.det(A))
print(np.linalg.matrix_rank(A))
print(np.dot(np.linalg.inv(A),f))
# б) 
# 2x1 − 4x2 + 6x3 =  1, 
#  x1 − 2x2 + 3x3 = −2,
# 3x1 − 6x2 + 9x3 =  5;
# число неизвестных равно числу уравнений (3), определитель матрицы коэфф. равен нулю, 
# но b -не лежит в подпространстве а: решений нет.
# по т.Кронеккера: rank(A)=1 < rank(A~)=2:  система несовместна,  решений нет.

print('b)')
B=np.array([[2,-4,6,1],[1,-2, 3,-2],[3,-6,9,5]])
print(np.linalg.det(B[:,0:3]))
print(np.linalg.matrix_rank(B[:,0:3]))
print(np.linalg.matrix_rank(B[:,0:4]))


# в) 
#  x1 + 2x2 + 5x3 =  4,
# 3x1 +  x2 − 8x3 = −2
# число неизвестных больше числа уравнений, система недоопределена
# ранг матрицы коэфф. равен рангу расширенной - решений бесконечно

print('c)')
C=np.array([[1,2,5,4],[3,1,-8,-2]])
print(np.linalg.matrix_rank(C[:,0:4]))
print(np.linalg.matrix_rank(C))


a)
32.0
3
[1. 2. 3.]
b)
0.0
1
2
c)
2
2


In [53]:
#3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений,
# заданная расширенной матрицей
# A =         f = 
# 1 3 -2 4       3
# 0 5  0 1       2
# 0 0  3 0       4
# 0 0  0 2       1
A= np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])
print(np.linalg.matrix_rank(A[:,0:4]))
print(np.linalg.matrix_rank(A[:,0:5]))
# ранг матрицы коэфф. равен рангу расширенной и равно числу переменных - решение единственное

4
4


In [ ]:
##### 4. Дана система линейных уравнений, заданная расширенной матрицей
# AA= 1 2 3 a
#     4 5 6 b  
#     7 8 9 c
# Найти соотношение между параметрами a b c, при которых система является несовместной 

# три столбца матрицы коэффициентов являются линейно зависимыми, чтобы были решения, необходимо, чтобы столбец свободных коэфф.
# лежал в подпространстве столбцов коэфф. (a,b,c) = k*(1,4,7) + m*(1,1,1)
# в противном случае система несовместна!

# lesson 7

In [56]:
# 1. Решить систему уравнений методом Крамера:
# а)   x1 - 2*x2 = 1    b) 2*x1 -   x2 + 5*x3 = 10
#    3*x1 - 4*x2 = 7       1*x1 + 1*x2 - 3*x3 = -2
#                          2*x1 + 4*x2 + 1*x3 =  1
A,A1,A2 = np.array([[1,-2],[3,-4]]), np.array([[1,-2],[7,-4]]), np.array([[1, 1],[3, 7]])
detA,detA1,detA2 = np.linalg.det(A),np.linalg.det(A1),np.linalg.det(A2)
x1,x2 = detA1/detA,detA2/detA
print('a)  ',x1,x2)
B ,B1 = np.array([[2,-1,5],[1,1,-3],[2,4,1]]),np.array([[10,-1,5],[-2,1,-3],[1,4,1]]),
B2,B3 = np.array([[2,10,5],[1,-2,-3],[2,1,1]]),np.array([[2,-1,10],[1,1,-2],[2,4,1]]), 
detB,detB1,detB2,detB3 = np.linalg.det(B),np.linalg.det(B1),np.linalg.det(B2),np.linalg.det(B3)
x1,x2,x3 = detB1/detB,detB2/detB,detB3/detB
print('b)  ',x1,x2,x3)

a)   4.999999999999998 1.9999999999999991
b)   2.0000000000000018 -1.0000000000000009 1.0000000000000004


In [ ]:
# 2. Найти L-матрицу LU-разложения для матрицы коэффициентов:
# а) 1  2  4     b)  1  1  2  4            
#    2  9 12         2  5  8  9
#    3 26 30         3 18 29 18
#                    4 22 53 33
# 
#L21= 2 L31=3 => U = 1  2  4 => L32=4 => U = 1  2  4 => L = 1 0 0
#                    0  5  4                 0  5  4        2 1 0
#                    0 20 18                 0  0  2        3 4 1
#
#
#L21= 2; L31= 3; L41= 4 => L32= 5;L42= 6;  => L43= 7  => L = 1 0 0 0
#U = 1  1  2  4      U = 1  1  2  4                          2 1 0 0
#    0  3  4  1          0  3  4  1                          3 5 1 0
#    0 15 23  6          0  0  3  1                          4 6 7 1
#    0 18 45 17          0  0 21 11 
#

In [ ]:
# 3. Решить систему линейных уравнений методом LU-разложения
#  2*x1 +   x2 + 3*x3 =   1
# 11*x1 + 7*x2 + 5*x3 = − 6
#  9*x1 + 8*x2 + 4*x3 = − 5
#
#           L21=5.5; L31=4.5;   L32=7/3         
# U=  2 1 3 =>  2   1   3    =>  2   1   3     L =   1  0   0
#    11 7 5     0 1.5 -11.5      0 1.5 -11.5       5.5  1   0
#     9 8 4     0 3.5  -9.5      0   0  52/3       4.5 7/3  1
#
# решаем Ly=b => y1=1; y2 = -6 - 5.5=-11.5; y3 = -5 -4.5 + 23/2 *7/3= 17.333333
# решаем Ux=y => x3*52/3 = 52/3   => x3= 1; 
#                1.5x2-11.5=-11.5 => x2= 0;
#               2x1+0+3 = 1       => x1= -1  => x={-1, 0, 1}

In [65]:
# 4. Решить систему линейных уравнений методом Холецкого
#  81*x1 − 45*x2 + 45*x3 =   531
# −45*x1 + 50*x2 − 15*x3 = − 460
#  45*x1 − 15*x2 + 38*x3 =   193
# Матрица А - симметрична, невырождена и положительно определена:
A = np.array([[81,-45,45],[-45,50,-15],[45,-15,38]])
print('det(A)= ',np.linalg.det(A))
np.linalg.eig(A)

det(A)=  18225.000000000007


(array([134.72475295,   4.55103023,  29.72421681]),
 array([[ 0.76360931, -0.62869675,  0.14710953],
        [-0.48169913, -0.40297852,  0.77818652],
        [ 0.42996136,  0.66509301,  0.61056083]]))

In [ ]:
# тогда существует единственное представление: A=L*L.T
# найдем нижнюю треуг.матрицу L
# L11 = 9, L21=-5, L31= 5;                               9  0  0
# L22 = sqrt(50 - 5*5)=5 L32 =(-15-(-5*5))/5= 2;  => L= -5  5  0
# L33 = sqrt(38 - 5*5 -2*2) = 3                          5  2  3

# теперь решаемпоследовательно: Ly = b и L.Tx = y
# y1 = 531/9 = 59; y2 = (-460 +5*59)/5= -33; y3= (193-5*59 +2*33)/3= -12
# x3 = -12/3=-4; x2=(-33+8)/5=-5; x1= (59 +20 - 25)/9 =6;
# x={6,-5,-4}

In [ ]:
# 5*. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ